from typing import TextIO

from sd_train.infra.environment.types import FileServerSession, RunResult


class Environment:
    async def connect(self) -> None: ...
    async def close(self) -> None: ...
    async def run(
        self,
        command: str,
        stdout: TextIO | None = None,
        stderr: TextIO | None = None,
    ) -> RunResult: ...
    async def health_check(self) -> bool: ...
    async def __aenter__(self) -> "Environment": ...
    async def __aexit__(self, exc_type, exc, tb) -> None: ...
    async def start_file_server(self) -> FileServerSession | None: ...
    async def stop_file_server(self) -> None: ...
    async def file_server_status(self) -> FileServerSession | None: ...

    def sync_from_local(self, src: str, dst: str) -> None: ...
    def sync_to_local(self, src: str, dst: str, include_paths: list[str] | None = None) -> None: ...
